alter table public.staff_master add column if not exists platform_country text;
alter table public.staff_master add column if not exists resign_date date;
alter table public.staff_master add column if not exists work_telegram text;
alter table public.staff_master add column if not exists backend_account text;
alter table public.staff_master add column if not exists bank_account text;
alter table public.staff_master add column if not exists bank_holder text;
alter table public.staff_master add column if not exists bank_name text;

create table if not exists public.staff_events (
  id uuid primary key default gen_random_uuid(), employee_id text, staff_name text,
  event_type text not null check (event_type in ('resign','mistake','deduct','exam','offday')),
  event_date date, amount numeric, exam_score numeric, details text, notes text,
  status text not null default 'submitted', created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.staff_attachments (
  id uuid primary key default gen_random_uuid(), event_id uuid references public.staff_events(id) on delete cascade,
  employee_id text, file_path text not null, media_type text, original_name text,
  created_by uuid default auth.uid(), created_at timestamptz not null default now()
);
create table if not exists public.staff_monthly_performance (
  id bigint generated by default as identity primary key, employee_id text not null,
  period date not null, source_sheet text, payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), unique(employee_id,period,source_sheet)
);

alter table public.staff_events enable row level security;
alter table public.staff_attachments enable row level security;
alter table public.staff_monthly_performance enable row level security;
grant select,insert,update,delete on public.staff_master,public.staff_events,public.staff_attachments,public.staff_monthly_performance to authenticated;
grant usage,select on all sequences in schema public to authenticated;
drop policy if exists "Authenticated staff write" on public.staff_master;
create policy "Authenticated staff write" on public.staff_master for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated events write" on public.staff_events;
create policy "Authenticated events write" on public.staff_events for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated attachments write" on public.staff_attachments;
create policy "Authenticated attachments write" on public.staff_attachments for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated performance read" on public.staff_monthly_performance;
create policy "Authenticated performance read" on public.staff_monthly_performance for select to authenticated using (true);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('staff-media','staff-media',false,52428800,array['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','video/webm'])
on conflict(id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Authenticated staff media read" on storage.objects;
create policy "Authenticated staff media read" on storage.objects for select to authenticated using(bucket_id='staff-media');
drop policy if exists "Authenticated staff media upload" on storage.objects;
create policy "Authenticated staff media upload" on storage.objects for insert to authenticated with check(bucket_id='staff-media');
drop policy if exists "Authenticated staff media update" on storage.objects;
create policy "Authenticated staff media update" on storage.objects for update to authenticated using(bucket_id='staff-media') with check(bucket_id='staff-media');
drop policy if exists "Authenticated staff media delete" on storage.objects;
create policy "Authenticated staff media delete" on storage.objects for delete to authenticated using(bucket_id='staff-media');
